definitions_dict = {
    "createdbyname": "Name of the user who created the record : Field unused and automatically generated by Dataverse",
    "createdonbehalfbyname": "Name of the user on whose behalf the record was created : Field unused and automatically generated by Dataverse",
    "modifiedbyname": "Name of the user who last modified the record : Field unused and automatically generated by Dataverse",
    "modifiedonbehalfbyname": "Name of the user on whose behalf the record was last modified : Field unused and automatically generated by Dataverse",
    "owneridname": "Name of the owner of the record : Field unused and automatically generated by Dataverse",
    "owningbusinessunitname": "Name of the business unit that owns the record : Field unused and automatically generated by Dataverse",
    "statecodename": "State code of the record : Field unused and automatically generated by Dataverse",
    "statuscodename": "Status code of the record : Field unused and automatically generated by Dataverse",
}
